travis:
  secure:
    BINSTAR_TOKEN: nssH8WFzoVWKuC8t0RAaiAn7S5etdw2tdf5ELrMYm1gSHF0PHIsjoyqpSi2vUtnWwWM5x+B9uPra4XRW4vt6rcMPgDkk9KK/Q6LUBSzQdSOeKlp2hrkG17UU6TZPcZTfUcP2QqE2BRg9qOa9gznsJMoQuCQ/YQAHFQj32Juu2v404JtndTZmsHADNX881fdrobrSUm7ZXW5JUDPdBB+dRWIa6GKYXj6BU1LHa/9K3wqj4wRsCHE5XEOu9bRh/RG0jl4TtH5KCGFpl+ruAX+igYzwGRGVzr+8Av/LXXmtGGToxj9fQEvXTaJVm4IegudXiw91p4HPs42mVTkw9yjAdQ0i+ZzgjlaMa/pMlgk7ekA/gxw4NPLKpY6jaEIgYQE23msK+S7nHzSD+NXfAuSj4Fx4hVE3rDzTPigcKAIyL1TGS8Giws8Se7IkymFING9EuRD5C2gJHDxTFcvjyyjmHK215y5eo3LrgVP491HlSf7zzHXJXr/+165u/JT6GcFp9ymSsdGeGbZs7WwGU4FnSGf/DRFrC3Y3mXJ5TSeirIJn5kaj7KAUhUJ3lq2qTe0654HrogVeFro2KB2nTn+4+QW/nBtbSSdcSnIrOhdZAWnGn9FPYHhotu0DAM4czYuB40vap6IhDZSLhSuPkLxvECQPcMcZfhLRdARFsRc35NA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
