travis:
  secure:
    BINSTAR_TOKEN: Uo84NAbm2ldNWgv5ThYR6s2z8Qp7OTVrB9Oroo7VWAm0of8AJrDagMGs4CjNaeIGlSDH1MbPMd7QvjmZL2n2GEYuqiH2pGtJSJRLrdNPsoqfzkVTRf/2aXrxbXa3tS1b6WbteawkiJMD8kllg/2h8L5HX9YxpgDXYTFFthlvnvmqff2FqWKdJ05mwtu0bdn1/Bj8m9NPBq2Vcffk+I5GLxBX2BI0UCDjmbogjc390a7jZvhZLE3LHG9gZuthXeC47s6kgR/aNJ7NIUSDr6gIgXnTBLv/M9ZzOM8i6iM9PZopComsgYq9Q80P7QJnP03IYzscKx8cGO56dRQY/kdf04cvUzu2RBjwwgKoN847z00q2ldo/yjRreLoZxiczq0T3J5+zxSdesEC3CQFfAcdA8BZv/pViMCoXBnHRjY7THm2DClPFSLeW8UKvhyOOUfbn5xXyuTzK6j9rT0ikB7NAkYvRtOHkpUNBRCMWLcgVUUeArHY/gP4q7+k1H6yVmvMLsOdtTamdGV61YmoKcxaldBYkXtWhLWr0hdcoG1n1mXA1dVcLibbhYny8/T5hbV3LSZ10yN/qzhvtsBzl84mV83IY8zThVe1ytT00Lsd4hjiTbZ6JT/XvF4qJqMtO2+Numgrbi5PRqIjF5KiCEm6+31uN0X9Pd6Ha2YhKOcC954=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
